//FILE LIST THE NAME OF ACTIONS
export default {
  LOCATIONS_RECEIVED: 'LOCATIONS_RECEIVED',
  LOCATION_CREATED: 'LOCATION_CREATED',
  SELECT_LOCATION: 'SELECT_LOCATION',
  COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
  COMMENT_CREATED: 'COMMENT_CREATED',
}
